FROM takawang/gozmq:pull #TODO
MAINTAINER Taka Wang <taka@cmwang.net>

WORKDIR /go
RUN go get -u github.com/taka-wang/psmb

## Load app files
ADD . /go/src/github.com/taka-wang/psmb/tcp-srv/test/dummy-srv
WORKDIR /go/src/github.com/taka-wang/psmb/tcp-srv/test/dummy-srv
RUN go get -t ./...

## Default command
CMD ["go", "test", "-v"]
