# drone.io:0.5

pipeline:

    ci:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose rm -f -a
            - docker-compose pull
            - docker-compose build
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a

    test-dbwds:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose -f dbwds/docker-compose.yml rm -f -a
            - docker-compose -f dbwds/docker-compose.yml pull
            - docker-compose -f dbwds/docker-compose.yml build
            - docker-compose -f dbwds/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f dbwds/docker-compose.yml stop
            - docker-compose -f dbwds/docker-compose.yml rm -f -a

    test-cron:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true cron/.

    test-mreader:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mrds/.

    test-mwriter:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mrds/.

    test-psmb:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true .

    test-psmb-tcp:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true tcp/.

