# taka's private drone server
# for v0.5

pipeline:
    ci:
        image: takawang/dind:push # docker in docker wiht compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker-compose rm -f -a
            - docker-compose build
            - docker-compose up --abort-on-container-exit