build:
    mbd:
        image: takawang/ubuntu-modbus
        commands:
            - docker build -t takawang/mbd test/mb/.
            - docker run -v /tmp:/tmp -itd --name=mbd takawang/mbd
    psmb:
        image: takawang/ubuntu-gozmq
        commands:
            - docker build -t takawang/psmb .
            - docker run -v /tmp:/tmp -itd --name=psmb takawang/psmb
    goclient:
        image: takawang/ubuntu-gozmq
        commands:
            - docker build -t takawang/psmb-goclient test/goclient/.
            - docker run -v /tmp:/tmp --link mbd -it takawang/psmb-goclient
