build:
    psmb:
        image: takawang/ubuntu-gozmq
        commands:
            - go get github.com/marksalpeter/sugar
            - go get github.com/taka-wang/zmq3
            - go get github.com/taka-wang/gocron
            - go build
            - go test -v
