# drone.io:0.5

pipeline:

    ci:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/tmp:/var/tmp # for test
        commands:
            - docker-compose rm -f -a
            #- docker-compose rm -f -a
            - docker-compose pull
            - docker-compose build --no-cache
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a
            - cat /var/tmp/success      # test
            - rm -f /var/tmp/success    # cleanup

    test-mgo-history:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/tmp:/var/tmp # for test
        commands:
            - docker-compose -f mgo-history/docker-compose.yml rm -f -a
            - docker-compose -f mgo-history/docker-compose.yml pull
            - docker-compose -f mgo-history/docker-compose.yml build --no-cache
            - docker-compose -f mgo-history/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f mgo-history/docker-compose.yml stop
            - docker-compose -f mgo-history/docker-compose.yml rm -f -a
            - cat /var/tmp/success      # test
            - rm -f /var/tmp/success    # cleanup

    test-redis-writer:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/tmp:/var/tmp # for test
        commands:
            - docker-compose -f redis-writer/docker-compose.yml rm -f -a
            - docker-compose -f redis-writer/docker-compose.yml pull
            - docker-compose -f redis-writer/docker-compose.yml build --no-cache
            - docker-compose -f redis-writer/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f redis-writer/docker-compose.yml stop
            - docker-compose -f redis-writer/docker-compose.yml rm -f -a
            - cat /var/tmp/success      # test
            - rm -f /var/tmp/success    # cleanup

    test-redis-history:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/tmp:/var/tmp # for test
        commands:
            - docker-compose -f redis-history/docker-compose.yml rm -f -a
            - docker-compose -f redis-history/docker-compose.yml pull
            - docker-compose -f redis-history/docker-compose.yml build #--no-cache
            - docker-compose -f redis-history/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f redis-history/docker-compose.yml stop
            - docker-compose -f redis-history/docker-compose.yml rm -f -a
            - cat /var/tmp/success      # test
            - rm -f /var/tmp/success    # cleanup


    test-psmbtcp-srv:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true tcp-srv/.

    test-psmb-tcp:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true tcp/.

    test-cron:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true cron/.

    test-mem-reader:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mem-reader/.

    test-mem-reader:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mem-writer/.

    test-psmb:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true .
