build:
    mbd:
        image: takawang/ubuntu-modbus
        commands:
            - cd /
            - git clone https://github.com/taka-wang/modbusd.git
            - mkdir -p /modbusd/build
            - cd  /modbusd/build
            - cmake .. && make && make install
            - cd /modbusd/
            - cp "config/service.sh" "/etc/init.d/modbusd" && chmod +x /etc/init.d/modbusd && update-rc.d modbusd defaults
            - service modbusd start
            - cd /modbusd/tests/cmbserver
            - gcc server.c -o server -Wall -std=c99 `pkg-config --libs --cflags libmodbus`
            - /modbusd/tests/cmbserver/server &
    psmb:
        image: takawang/ubuntu-gozmq
        commands:
            - go get github.com/marksalpeter/sugar
            - go get github.com/taka-wang/zmq3
            - go get github.com/taka-wang/gocron
            - go build
            - go test -v
