# drone.io:0.5

pipeline:
#
# Save Bandwidth
#
#    publish:
#        image: takawang/dind:push
#        volumes:
#            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
#        commands:
#            - docker build --no-cache=true -t takawang/psmb:x86 .
#            - docker push takawang/psmb:x86

    psmb-test:
        image: takawang/dind # docker in docker wiht compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker build .

    psmbtcp-test:
        image: takawang/dind # docker in docker wiht compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker build tcp/.

    ci:
        image: takawang/dind # docker in docker wiht compose
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock # docker in docker trick
        commands:
            - docker-compose rm -f -a
            - docker-compose pull # pull
            - docker-compose build
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a