# drone.io:0.5

pipeline:

    test-psmb:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true .

    test-psmb-tcp:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true tcp/.

    ci:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose rm -f -a
            - docker-compose pull
            - docker-compose build
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a