# drone.io:0.5

pipeline:

    test-psmb:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build .

    test-psmbtcp:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build tcp/.

    ci:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose rm -f -a
            - docker-compose pull
            - docker-compose build
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a