build:
    psmb_goclient:
        image: takawang/ubuntu-drone-psmb
        commands:
            - git clone https://github.com/taka-wang/modbusd.git
            - mkdir -p modbusd/build
            - cd  modbusd/build
            - cmake .. && make && make install
            - cd ..
            - cp "config/service.sh" "/etc/init.d/modbusd" && chmod +x /etc/init.d/modbusd && update-rc.d modbusd defaults
            - service modbusd start
            - cd tests/cmbserver
            - gcc server.c -o server -Wall -std=c99 `pkg-config --libs --cflags libmodbus`
            - ./server &
            - cd ../../../

            - go get github.com/marksalpeter/sugar
            - go get github.com/taka-wang/zmq3
            - go get github.com/taka-wang/gocron
            - go test -v
            - go build -o psmb
            - ./psmb &

            - cd test/goclient/
            - go get github.com/marksalpeter/sugar 
            - go test -v
