# drone.io v0.4
# armhf


build:
    image: takawang/dind:$$arch
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/tmp:/var/tmp # for test
    privileged: true
    commands:
        # build cache
        - docker build -t golang:armhf-cache -f release/Dockerfile.armhf-cache .
        # build builder
        - docker build -t builder:armhf --no-cache=true -f release/Dockerfile.armhf-build .
        - docker run -itd --name=builder builder:armhf
        # copy binary to release folder
        - docker cp builder:/psmb-srv release/
        # build release image
        - docker build -t edgepro/psmb-srv:armhf --no-cache=true -f release/Dockerfile.armhf-pack release/.
        - docker push edgepro/psmb-srv:armhf
        # clean up
        - docker rm -f builder
        - docker rmi -f builder:armhf
        ### ci ######
        - docker-compose -f docker-compose.$$arch rm -f -a
        #- docker-compose pull
        - docker-compose -f docker-compose.$$arch build --no-cache
        - docker-compose -f docker-compose.$$arch up --abort-on-container-exit
        #- docker-compose -f docker-compose.$$arch stop
        #- docker-compose -f docker-compose.$$arch rm -f -a
        - cat /var/tmp/success      # test
        - rm -f /var/tmp/success    # cleanup

matrix:
    arch:
        - armhf

