# drone.io:0.5

pipeline:

    test-rhistory: # redis-based history data store
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose -f rhistory/docker-compose.yml rm -f -a
            - docker-compose -f rhistory/docker-compose.yml pull
            - docker-compose -f rhistory/docker-compose.yml build
            - docker-compose -f rhistory/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f rhistory/docker-compose.yml stop
            - docker-compose -f rhistory/docker-compose.yml rm -f -a

    test-dbwds: # redis-based writer data store
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose -f dbwds/docker-compose.yml rm -f -a
            - docker-compose -f dbwds/docker-compose.yml pull
            - docker-compose -f dbwds/docker-compose.yml build
            - docker-compose -f dbwds/docker-compose.yml up --abort-on-container-exit
            - docker-compose -f dbwds/docker-compose.yml stop
            - docker-compose -f dbwds/docker-compose.yml rm -f -a

    test-cron: # scheduler
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true cron/.

    test-mreader: # in-memory reader data store
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mrds/.

    test-mwriter: # in-memory writer data store
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true mrds/.

    test-psmb: # psmb lib
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true .

    test-psmb-tcp: # psmb/tcp lib
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker build --no-cache=true tcp/.

    ci:
        image: takawang/dind
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        commands:
            - docker-compose rm -f -a
            - docker-compose pull
            - docker-compose build
            - docker-compose up --abort-on-container-exit
            - docker-compose stop
            - docker-compose rm -f -a