sudo: required

services:
- docker

before_install:
# set timezone
- export TZ=Asia/Taipei

install:
# login to dockerhub
- docker login --email=$DOCKER_HUB_EMAIL --username=takawang --password=$DOCKER_HUB_PASSWORD

script:

### build modbus slave server image
- docker build -t $PSMB_MODBUS_IMG test/mb/.
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $PSMB_MODBUS_IMG:latest $PSMB_MODBUS_IMG:$TRAVIS_TAG; fi && docker push $PSMB_MODBUS_IMG

### build psmb image
- docker build -t $PSMB_IMG .
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $PSMB_IMG:latest $PSMB_IMG:$TRAVIS_TAG; fi && docker push $PSMB_IMG

### build goclient image
- docker build -t $PSMB_GOCLIENT_IMG test/goclient/.
- if [ ! -z "$TRAVIS_TAG" ]; then docker tag $PSMB_GOCLIENT_IMG:latest $PSMB_GOCLIENT_IMG:$TRAVIS_TAG; fi && docker push $PSMB_GOCLIENT_IMG

### run modbus
- docker run -v /tmp:/tmp -itd --name=$PSMB_MODBUS_NAME $PSMB_MODBUS_IMG

### run psmb
- docker run -v /tmp:/tmp -itd --name=$PSMB_NAME $PSMB_IMG

### run goclient
- docker run -v /tmp:/tmp --link $PSMB_MODBUS_NAME -it --name=$PSMB_GOCLIENT_NAME $PSMB_GOCLIENT_IMG

### stop all containers
- docker stop $PSMB_MODBUS_NAME $PSMB_NAME $PSMB_GOCLIENT_NAME


env:
  global:

  - PSMB_MODBUS_IMG=takawang/mbd
  - PSMB_MODBUS_NAME=mbd
  - PSMB_IMG=takawang/psmb
  - PSMB_NAME=psmb
  - PSMB_GOCLIENT_IMG=takawang/psmb-goclient
  - PSMB_GOCLIENT_NAME=goclient

notifications:
  email: false
  hipchat:
    on_success: always
    rooms:
      secure: aklONboOLgu63ji6MvOv6fkhMiL1lP5SBsq35iMfRdqFSrH7qzXEC8AHYvI71gjE19XRblNnWahinJVNGXih9Aw44JfZc7+/RlEZPNvnT3JCKwKYubwdure8mBuxE+04Eg0BNp9XLoVlw/RX9ejeCK90OkhKd3wBHuNwIWaqSYMSEEK1Ye95r4Rx62OH0n+yHnjmKULKM9+axFBIb6Kymz+lPIjb+hWNdmtDpGWwPpmUBomTY6PRaOS4KXMcuOlBlCqQmT4O7Z+uqjuXwg7LwWXhdwQeuPvCdwnT03ENahnuNVAFl6xbqYZnwyNd/9utzvOFwZLw7cqm5Im5IY7sl60Yi/DD00RZne5AibE3l81q33+rUY9+c8X4R6YlfzICrKwBL/7bhfhhFUHj2xlpmFnUc8mwebQg8xb+szNePQucyFrB+/Dcyyk/Hi3zmLhhGfsBWeA0bEVrknh/q8zLOMDrTQnc2uUr4Gn4lHYzDbQQgsuGrs6vV4KjJAD3Z9JQ+Z5OfITFuGVGLtGE5yY2pU9oLCKkpibNv/4gWqDkNKW0pwWLsJppi9lYuZe1ItnxkCwL3qJ33KEqHvVb5lvh9gDiBzzeuuuFewIadCQezwkE5hLLAw1QTqKjktz6JN1uTNE/1khgFYXNsSw6djhEh/eQieeA96QWL4QW9Jjr9eA=
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"