redis:
    image: redis:3.2.3-alpine
    ports:
        - "6379"

redis-history:
    build: ../.
    dockerfile: redis-history/Dockerfile
    links:
        - redis
    volumes: # mount for test
        - /var/tmp:/var/tmp
        - $PWD/shared:/shared
