FROM takawang/gozmq:pull # TODO change
MAINTAINER Taka Wang <taka@cmwang.net>

WORKDIR /go
RUN go get -u github.com/taka-wang/psmb/tcp

ADD . /go/src/github.com/taka-wang/psmb/tcp-srv
WORKDIR /go/src/github.com/taka-wang/psmb/tcp-srv
RUN go get -t ./... \
    && go build -o psmbtcp-srv \
    && cp psmbtcp-srv /usr/bin/ 

CMD /usr/bin/psmbtcp-srv

