mongodb:
    image: mongo:3.2
    ports:
        - "27017"

mgo-history:
    build: ../.
    dockerfile: mgo-history/Dockerfile
    links: 
        - mongodb
    volumes: # mount for test
        - /var/tmp:/var/tmp
        - $PWD/shared:/shared