redis:
    image: redis
    ports:
        - "6379"
redis-writer:
    build: ../.
    dockerfile: redis-writer/Dockerfile
    links:
        - redis
    volumes: # mount for test
        - /var/tmp:/var/tmp
        - $PWD/shared:/shared
