# armhf
FROM armv7/armhf-ubuntu:16.04
MAINTAINER Taka Wang <taka@cmwang.net>

ENV CONF_PSMBTCP "/etc/psmbtcp"
ENV EP_BACKEND "consul.cmwang.net:8500"
ENV ZMQ_VERSION 3.2.5

# add binary
ADD libzmq.so.3.0.0 /usr/lib/
ADD libzmq.so.3 /usr/lib/
ADD psmb-srv /

ENTRYPOINT /psmb-srv

EXPOSE 502