# TOML config begin

[log]
debug       = true                      # log level
json        = false                     # json formatter flag
to_file     = false                     # log to file flag
filename    = "/var/log/psmbtcp.log"    # log file location

[redis]
server              = "127.0.0.1"       # redis server ip
port                = "6379"            # redis server port
max_idel            = 3                 # maximum number of idle connections in the pool.
max_active          = 0                 # maximum number of connections allocated by the pool at a given time. When zero, there is no limit on the number of connections in the pool.
idel_timeout        = 30                # close connections after remaining idle for this duration. If the value is zero, then idle connections are not closed.

[mongo]
server              = "127.0.0.1"       # mongo server ip
port                = "27017"           # mongo server port
is_drop             = true              # drop table flag
connection_timeout  = 60                # timeout is the amount of time to wait for a server to respond when first connecting and on follow up operations in the session.
db_name             = "test"            # default database name
authentication      = false             # credentials flag
username            = "username"        # credentials
password            = "password"        # credentials

[mgo-history]
db_name             = "test"            # database name
collection_name     = "mbtcp:history"   # history collection name

[redis_history]
hash_name           = "mbtcp:latest"    # redis hash table name
zset_prefix         = "mbtcp:data:"     # redis zset key prefix

[redis_writer]
hash_name           = "mbtcp:writer"    # redis hash table name

[psmbtcp]
default_port            = "502"         # modbus slave default port
min_connection_timeout  = 200000        # minimal tcp connection timeout in ms
min_poll_interval       = 1             # minimal poll interval in second

[zmq]
[zmq.pub]
    upstream   = "ipc:///tmp/from.psmb"     # to services
    downstream = "ipc:///tmp/to.modbus"     # to modbusd
[zmq.sub]
    upstream   = "ipc:///tmp/to.psmb"       # from services
    downstream = "ipc:///tmp/from.modbus"   # from modbusd

# TOML config end @20160806