FROM takawang/gozmq:pull #TODO change
MAINTAINER Taka Wang <taka@cmwang.net>

WORKDIR /go
RUN go get -u github.com/taka-wang/psmb

## Load app files
ADD . /go/src/github.com/taka-wang/psmb/tcp
WORKDIR /go/src/github.com/taka-wang/psmb/tcp
RUN go get -t ./... && go test -v
